//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.03 at 06:11:00 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://stx.com/commands", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.stx.commands;
